
#define MOVESPEED_DATA_INDEX_PRIORITY 1
#define MOVESPEED_DATA_INDEX_FLAGS 2
#define MOVESPEED_DATA_INDEX_OLDSTYLE_SLOWDOWN 3

//flags
#define IGNORE_NOSLOW	(1 << 0)

//ids

#define MOVESPEED_ID_MOB_WALK_RUN_CONFIG_SPEED			"MOB_WALK_RUN"

#define MOVESPEED_ID_SLIME_CONFIG_SPEEDMOD				"SLIME_CONFIG_MODIFIER"
#define MOVESPEED_ID_SLIME_REAGENTMOD					"SLIME_REAGENT_MODIFIER"
#define MOVESPEED_ID_SLIME_HEALTHMOD					"SLIME_HEALTH_MODIFIER"
#define MOVESPEED_ID_SLIME_TEMPMOD						"SLIME_TEMPERATURE_MODIFIER"

#define MOVESPEED_ID_LIVING_TURF_SPEEDMOD				"LIVING_TURF_SPEEDMOD"

#define MOVESPEED_ID_CARBON_SOFTCRIT					"CARBON_SOFTCRIT"
#define MOVESPEED_ID_CARBON_OLDSPEED					"CARBON_DEPRECATED_SPEED"

#define MOVESPEED_ID_MONKEY_CONFIG_SPEEDMOD				"MONKEY_CONFIG_SPEEDMOD"
#define MOVESPEED_ID_MONKEY_REAGENT_SPEEDMOD			"MONKEY_REAGENT_SPEEDMOD"
#define MOVESPEED_ID_MONKEY_TEMPERATURE_SPEEDMOD		"MONKEY_TEMPERATURE_SPEEDMOD"
#define MOVESPEED_ID_MONKEY_HEALTH_SPEEDMOD				"MONKEY_HEALTH_SPEEDMOD"

#define MOVESPEED_ID_HUMAN_CONFIG_SPEEDMOD				"HUMAN_CONFIG_SPEEDMOD"
#define MOVESPEED_ID_HUMAN_OLDSPECIES					"HUMAN_DEPRECATED_SPECIES"

#define MOVESPEED_ID_SIMPLEMOB_CONFIG_SPEEDMOD			"SIMPLEMOB_CONFIG_MODIFIER"
#define MOVESPEED_ID_SIMPLEMOB_VARSPEED					"SIMPLEMOB_VARSPEED_MODIFIER"

#define MOVESPEED_ID_ALIEN_CONFIG_SPEEDMOD				"ALIEN_CONFIG_MODIFIER"
#define MOVESPEED_ID_ALIEN_QUEEN_SPEEDMOD				"ALIEN_QUEEN_MODIFIER"
#define MOVESPEED_ID_ALIEN_PRAETORIAN_SPEEDMOD			"ALIEN_PRAETORIAN_MODIFIER"
#define MOVESPEED_ID_ALIEN_HUNTER_SPEEDMOD				"ALIEN_HUNTER_MODIFIER"

#define MOVESPEED_ID_PAI_INNATE_SPEEDMOD				"PAI_INNATE_MODIFIER"
#define MOVESPEED_ID_PAI_SPACEWALK_SPEEDMOD				"PAI_SPACEWALK_MODIFIER"

//args for certain (constant) modifiers
#define MOVESPEED_MODIFIER_ALIEN_QUEEN					MOVESPEED_ID_ALIEN_QUEEN_SPEEDMOD,					100,	oldstyle_slowdown = 3
#define MOVESPEED_MODIFIER_ALIEN_PRAETORIAN				MOVESPEED_ID_ALIEN_PRAETORIAN_SPEEDMOD,				100,	oldstyle_slowdown = 1
#define MOVESPEED_MODIFIER_ALIEN_HUNTER					MOVESPEED_ID_ALIEN_HUNTER_SPEEDMOD,					100,	oldstyle_slowdown = -1

#define MOVESPEED_MODIFIER_PAI_INNATE					MOVESPEED_ID_PAI_INNATE_SPEEDMOD,					100,	oldstyle_slowdown = 1
#define MOVESPEED_MODIFIER_PAI_SPACEWALK				MOVESPEED_ID_PAI_SPACEWALK_SPEEDMOD,				100,	oldstyle_slowdown = 2

